server:
  port: 8500
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/amroczkowski/altkom-animal-hotel-configuration.git
